---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "intesa-lab-python-api"
  namespace: "intesalab"
  labels:
    app: "intesa-lab-python-api"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "intesa-lab-python-api"
  template:
    metadata:
      labels:
        app: "intesa-lab-python-api"
        version: v1
    spec:
      containers:
      - name: "intesa-lab-python-api"
        image: "thingsolver/intesa-lab-python-api:1.0"
        imagePullPolicy: Always
        command: ["python"]
        args: ["/app/main.py"]
