---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "intesa-lab-python-api"
  namespace: "default"
  labels:
    app: "intesa-lab-python-api"
    version: v1
spec:
  ports:
  - name: http-intesa-lab-python-api
    port: 8080
    targetPort: 8080
  selector:
    app: "intesa-lab-python-api"
  type: "ClusterIP"