---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "intesa-lab-wait-init"
  namespace: "intesalab"
  labels:
    app: "intesa-lab-wait-init"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "intesa-lab-wait-init"
  template:
    metadata:
      labels:
        app: "intesa-lab-wait-init"
        version: v1
    spec:
      containers:
      - name: "intesa-lab-wait-init"
        image: "thingsolver/intesa-lab-python-api:1.0"
        imagePullPolicy: Always
        command: ["python"]
        args: ["/app/main.py"]
        volumeMounts:
        - name: config-map-cp
          mountPath: /app/main.py
          subPath: main.py
      volumes:
        - name: config-map-cp
          configMap:
            name: intesalab-main-cfg
      initContainers:
      - name: init-container
        image: ibmcom/curl:4.0.0
        command: ['sh', '-c', "until nslookup my-nginx; do sleep 2; done"]