---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "intesa-lab-python-api-with-config-maps"
  namespace: "intesalab"
  labels:
    app: "intesa-lab-python-api-with-config-maps"
    version: v1
spec:
  ports:
  - name: http-intesa-lab-python-api-with-config-maps
    port: 8080
    targetPort: 8080
  selector:
    app: "intesa-lab-python-api-with-config-maps"
  type: "ClusterIP"